### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by alvarezloaiciga** [christian-marie/ns_connector#7]
Hi @christian-marie can you release the version `0.0.18` please? I need this change: https://github.com/christian-marie/ns_connector/commit/21657e2206fde2c891dd91044dd8c32351cdd004

**Comment by christian-marie** [comment]
Hi Jose, that's done.

I decided to bump to 0.1.0 as the API Seems pretty stable: https://rubygems.org/gems/ns_connector/versions/0.1.0
